version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: todos
    volumes:
      - db_data:/var/lib/mysql
      - ./script/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  db_data: {}
